[project]
name = "rna-rl"
version = "0.3.0"
description = "RL + MCTS sandbox for RNA folding"
authors = [{name = "Your Name"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["numpy>=1.22"]

[project.optional-dependencies]
torch = ["torch>=2.1"]
dev = ["pytest>=7.0"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"